### ISSUE TITLE
Android.Eis4TY.XRStereoscopicViewer

### ISSUE THREAD

**Issue by maxlu06** [Eis4TY/XR-Stereoscopic-Viewer#1]
找不到Android.Eis4TY.XRStereoscopicViewer文件夹，是要放在sdcard的根目录下么？

**Comment by Eis4TY** [comment]
路径应该是类似于： 此电脑\Quest Pro\内部共享存储空间\Android\data\com.Eis4TY.XRStereoscopicViewer\files。
如果看不到 'XRStereoscopicViewer' 文件夹，试试先打开应用程序再关闭。应该就有了

**Comment by maxlu06** [comment]
我把文件放到了 Android\data\com.Eis4TY.XRStereoscopicViewer\files 目录下，但进去后还是空的

**Comment by Eis4TY** [comment]
你要在这个目录下建立一个叫 'Media' 的文件夹，再把图片放进去

**Comment by maxlu06** [comment]
搞定，感谢！~
