### ISSUE TITLE
Question for function ChangeImgIPD

### ISSUE THREAD

**Issue by xingyi5166** [Eis4TY/XR-Stereoscopic-Viewer#20]
Hi,

I want to change the default value for IPD. I tried to change in the UI of Unity but not working. Then I tried to change it in the function below but still not working. Can you give some hints? Thanks!

    private void Start()
    {
        if (targetSlider)
        {
            targetSlider.onValueChanged.AddListener(OnSliderValueChanged);
        }

        UpdateTextValue(targetSlider.value);
        ChangeImgIPD(0.02f);
    }

**Comment by Eis4TY** [comment]
> Hi, 你好，
> 
> I want to change the default value for IPD. I tried to change in the UI of Unity but not working. Then I tried to change it in the function below but still not working. Can you give some hints? Thanks!我想更改 IPD 的默认值。我尝试更改 Unity 的 UI，但没有成功。然后我尝试在下面的函数中更改它，但仍然不起作用。你能给一些提示吗？谢谢！
> 
> ```
> private void Start()
> {
>     if (targetSlider)
>     {
>         targetSlider.onValueChanged.AddListener(OnSliderValueChanged);
>     }
> 
>     UpdateTextValue(targetSlider.value);
>     ChangeImgIPD(0.02f);
> }
> ```

sorry I didn't see it. Have you solved the problem now？

**Comment by xingyi5166** [comment]
> > Hi, 你好，
> > I want to change the default value for IPD. I tried to change in the UI of Unity but not working. Then I tried to change it in the function below but still not working. Can you give some hints? Thanks!我想更改 IPD 的默认值。我尝试更改 Unity 的 UI，但没有成功。然后我尝试在下面的函数中更改它，但仍然不起作用。你能给一些提示吗？谢谢！
> > ```
> > private void Start()
> > {
> >     if (targetSlider)
> >     {
> >         targetSlider.onValueChanged.AddListener(OnSliderValueChanged);
> >     }
> > 
> >     UpdateTextValue(targetSlider.value);
> >     ChangeImgIPD(0.02f);
> > }
> > ```
> 
> sorry I didn't see it. Have you solved the problem now？

Thanks, it is already be solved.
