### ISSUE TITLE
苹果空间视频转换mp4后无法加载

### ISSUE THREAD

**Issue by rover95** [Eis4TY/XR-Stereoscopic-Viewer#23]
使用ios第三方应用转换空间视频，h264的mp4，西洋镜中一直是loading状态加载不出来，大佬能看看是什么原因吗，使用其他的3d视频软件是能播放的
![image](https://github.com/user-attachments/assets/2a51c1e9-4cf0-4908-a5a9-2132ef2f21f6)

**Comment by Eis4TY** [comment]
这个我也不清楚是什么原因，要不换别的第三方导出工具试试

**Comment by rover95** [comment]
> 这个我也不清楚是什么原因，要不换别的第三方导出工具试试

我后来试了，用ffmpeg删除视频的音轨就能加载了，这个播放器不支持带音频的sbs视频吗

**Comment by Eis4TY** [comment]
支持，可能是特殊的音频格式或码率不支持
