### ISSUE TITLE
希望能有SBS Half支持。

### ISSUE THREAD

**Issue by Kas1o** [Eis4TY/XR-Stereoscopic-Viewer#25]
SBS Half中，媒体的宽度将会被缩放至0.5x，常见于3D视频中。
Example Image：
![Jensen_LR](https://github.com/user-attachments/assets/49105e13-28a7-42a5-a8dd-3a3fecd69084)

**Comment by Eis4TY** [comment]
半宽会损失横向像素，以后的标准都是全宽的了。之前的就手动转一下吧
