### ISSUE TITLE
拷贝Media到/sdcard/Android/data/com.Eis4TY.XRStereoscopicViewer后仍然加载不出图片

### ISSUE THREAD

**Issue by skylarkning** [Eis4TY/XR-Stereoscopic-Viewer#4]
打开应用后只能找到/sdcard/Android/data/com.Eis4TY.XRStereoscopicViewer，没有Andriod.Eis4TY.XRStereoscopicViewer这个目录。拷贝media文件夹进com.Eis4TY.XRStereoscopicViewer，应用内仍加载不出任何图片或视频

**Comment by Eis4TY** [comment]
> 打开应用后只能找到/sdcard/Android/data/com.Eis4TY.XRStereoscopicViewer，没有Andriod.Eis4TY.XRStereoscopicViewer这个目录。拷贝media文件夹进com.Eis4TY.XRStereoscopicViewer，应用内仍加载不出任何图片或视频

抱歉，应该把 "media文件夹" 放到 "\Android\data\com.Eis4TY.XRStereoscopicViewer\files" 文件夹下
